// Comprehensive country flag mapping for coffee origins
// Uses flag-icons CSS library with ISO 3166-1 alpha-2 country codes

export const getCountryFlagCode = (origin) => {
  const flagCodeMap = {
    // Americas
    'Brazil': 'br',
    'Colombia': 'co',
    'Guatemala': 'gt',
    'Nicaragua': 'ni',
    'Panama': 'pa',
    'Peru': 'pe',
    'Ecuador': 'ec',
    'Bolivia': 'bo',
    'Venezuela': 've',
    'Mexico': 'mx',
    'Dominican Republic': 'do',
    'Costa Rica': 'cr',
    'El Salvador': 'sv',
    'Haiti': 'ht',
    'Puerto Rico': 'pr',
    'Jamaica': 'jm',
    'Honduras': 'hn',

    // Africa
    'Ethiopia': 'et',
    'Kenya': 'ke',
    'Tanzania': 'tz',
    'Uganda': 'ug',
    'Rwanda': 'rw',
    'Burundi': 'bi',
    'Malawi': 'mw',
    'Zambia': 'zm',
    'Zimbabwe': 'zw',
    'Cameroon': 'cm',
    'Ivory Coast': 'ci',
    'Ghana': 'gh',
    'Togo': 'tg',
    'Angola': 'ao',
    'Democratic Republic of Congo': 'cd',
    'Central African Republic': 'cf',
    'Equatorial Guinea': 'gq',
    'Gabon': 'ga',
    'Madagascar': 'mg',
    'Mozambique': 'mz',
    'South Africa': 'za',

    // Asia-Pacific
    'India': 'in',
    'Indonesia': 'id',
    'Vietnam': 'vn',
    'Thailand': 'th',
    'Laos': 'la',
    'Myanmar': 'mm',
    'Philippines': 'ph',
    'China': 'cn',
    'Taiwan': 'tw',
    'Japan': 'jp',
    'South Korea': 'kr',
    'Australia': 'au',
    'Papua New Guinea': 'pg',
    'New Caledonia': 'nc',
    'Timor-Leste': 'tl',
    'Sri Lanka': 'lk',
    'Nepal': 'np',

    // Middle East & Other
    'Yemen': 'ye',
    'Turkey': 'tr',
    'Cyprus': 'cy',

    // Special cases
    'Hawaii': 'us', // Hawaii is part of USA
    'Puerto Rico': 'pr', // Has its own flag

    // Alternative spellings/names
    'USA': 'us',
    'United States': 'us',
    'United States of America': 'us',
    'Cote d\'Ivoire': 'ci',
    'Côte d\'Ivoire': 'ci',
    'East Timor': 'tl',
    'Burma': 'mm',
    'Republic of Korea': 'kr',
    'South Korea': 'kr',
    'Democratic People\'s Republic of Korea': 'kp',
    'North Korea': 'kp'
  };

  return flagCodeMap[origin] || null;
};

// Export the mapping for reference
export const countryFlagCodes = {
  'Brazil': 'br',
  'Colombia': 'co',
  'Guatemala': 'gt',
  'Nicaragua': 'ni',
  'Panama': 'pa',
  'Peru': 'pe',
  'Ecuador': 'ec',
  'Bolivia': 'bo',
  'Venezuela': 've',
  'Mexico': 'mx',
  'Dominican Republic': 'do',
  'Costa Rica': 'cr',
  'El Salvador': 'sv',
  'Haiti': 'ht',
  'Puerto Rico': 'pr',
  'Jamaica': 'jm',
  'Honduras': 'hn',
  'Ethiopia': 'et',
  'Kenya': 'ke',
  'Tanzania': 'tz',
  'Uganda': 'ug',
  'Rwanda': 'rw',
  'Burundi': 'bi',
  'Malawi': 'mw',
  'Zambia': 'zm',
  'Zimbabwe': 'zw',
  'Cameroon': 'cm',
  'Ivory Coast': 'ci',
  'Ghana': 'gh',
  'Togo': 'tg',
  'Angola': 'ao',
  'Democratic Republic of Congo': 'cd',
  'Central African Republic': 'cf',
  'Equatorial Guinea': 'gq',
  'Gabon': 'ga',
  'Madagascar': 'mg',
  'Mozambique': 'mz',
  'South Africa': 'za',
  'India': 'in',
  'Indonesia': 'id',
  'Vietnam': 'vn',
  'Thailand': 'th',
  'Laos': 'la',
  'Myanmar': 'mm',
  'Philippines': 'ph',
  'China': 'cn',
  'Taiwan': 'tw',
  'Japan': 'jp',
  'South Korea': 'kr',
  'Australia': 'au',
  'Papua New Guinea': 'pg',
  'New Caledonia': 'nc',
  'Timor-Leste': 'tl',
  'Sri Lanka': 'lk',
  'Nepal': 'np',
  'Yemen': 'ye',
  'Turkey': 'tr',
  'Cyprus': 'cy',
  'Hawaii': 'us',
  'USA': 'us',
  'United States': 'us',
  'United States of America': 'us'
};